#note: largely following xdem example
# left 'files: ' blank, wasn't sure how to specify yet
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  # Fix common spelling mistakes
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        args: ["--check-filenames"]
        types_or: [python, yaml, markdown]

  # Replace relative imports
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  # Format code using black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=120]

  # Lint code using flake8
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [
          '--max-line-length', '120',
          '--extend-ignore', 'E203,C408',
          '--'
        ]
        additional_dependencies:
          - flake8-comprehensions==3.1.0
          - flake8-bugbear==21.3.2

  # Sort imports using isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Automatically upgrade syntax to a minimum version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  # Various formattings
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
        types: [text]
        types_or: [python, rst]
      - id: rst-inline-touching-normal
        types: [text]
        types_or: [python, rst]
      - id: python-no-eval
      - id: python-use-type-annotations

  # Add custom regex lints (see .relint.yml)
  - repo: https://github.com/codingjoe/relint
    rev: 2.0.0
    hooks:
      - id: relint

  - repo: local
    hooks:
      - id: pip-to-conda
        name: Generate pip dependency from conda
        language: python
        entry: .github/scripts/generate_pip_deps_from_conda.py
        files: ^(environment.yml|requirements.txt)$
        pass_filenames: false
        additional_dependencies: [tomli, pyyaml]
